name: 'Prepare macOS Build'

description: 'Installs required packages for macOS builds.'

runs:
  using: "composite"
  steps:
    - name: Install required packages
      run: |
        # Required for macos-13
        pip install setuptools
        # Required for macos-14
        brew install python-setuptools
      shell: bash

