name: Build

on:
  push:
    branches:
      - master
    paths:
      - "**.cpp"
      - "**.h"
      - "**.java"

  pull_request:
    branches:
      - master

  workflow_dispatch:

env:
  WEBRTC_CACHE_BRANCH: 7204
  WEBRTC_CHECKOUT_FOLDER: webrtc
  WEBRTC_INSTALL_FOLDER: webrtc/build

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: macos_x86-64
            runs-on: macos-13
          - name: macos_arm64
            runs-on: macos-15
        java: [17]
    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: prepare-build
        name: Prepare build
        uses: ./.github/actions/prepare-macos

      - id: maven-build
        name: Maven build
        uses: ./.github/actions/build
        with:
          java-version: ${{ matrix.java }}
          platform-name: ${{ matrix.platform.name }}
          maven-username: ${{ secrets.MAVEN_USERNAME }}
          maven-password: ${{ secrets.MAVEN_TOKEN }}
